// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ddpc.DartSuite.Infrastructure.Persistence;

#nullable disable

namespace ddpc.DartSuite.Infrastructure.Migrations
{
    [DbContext(typeof(DartSuiteDbContext))]
    [Migration("20260406160722_RemoveUniqueIndexOnBoardExternalBoardId")]
    partial class RemoveUniqueIndexOnBoardExternalBoardId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoardManagerUrl")
                        .HasColumnType("text");

                    b.Property<int>("ConnectionState")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentMatchLabel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ExtensionStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalBoardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastExtensionPollUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocalIpAddress")
                        .HasColumnType("text");

                    b.Property<int>("ManagedMode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SchedulingStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayLegs")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("AwaySets")
                        .HasColumnType("integer");

                    b.Property<string>("AwaySlotOrigin")
                        .HasColumnType("text");

                    b.Property<Guid?>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ExpectedEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalMatchId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<int>("HomeLegs")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeSets")
                        .HasColumnType("integer");

                    b.Property<string>("HomeSlotOrigin")
                        .HasColumnType("text");

                    b.Property<bool>("IsBoardLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStartTimeLocked")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<string>("NextMatchInfo")
                        .HasColumnType("text");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PlannedEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PlannedStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("SchedulingStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WinnerParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Phase", "Round", "MatchNumber")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.MatchFollower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAccountName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "UserAccountName")
                        .IsUnique();

                    b.ToTable("MatchFollowers");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.MatchPlayerStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageDartsPerLeg")
                        .HasColumnType("double precision");

                    b.Property<int>("BestLegDarts")
                        .HasColumnType("integer");

                    b.Property<int>("Breaks")
                        .HasColumnType("integer");

                    b.Property<int>("CheckoutAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("CheckoutHits")
                        .HasColumnType("integer");

                    b.Property<double>("CheckoutPercent")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DartsThrown")
                        .HasColumnType("integer");

                    b.Property<double>("DoubleQuota")
                        .HasColumnType("double precision");

                    b.Property<double>("First9Average")
                        .HasColumnType("double precision");

                    b.Property<int>("HighestCheckout")
                        .HasColumnType("integer");

                    b.Property<int?>("HighestRoundScore")
                        .HasColumnType("integer");

                    b.Property<int>("LegsLost")
                        .HasColumnType("integer");

                    b.Property<int>("LegsWon")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Plus100")
                        .HasColumnType("integer");

                    b.Property<int>("Plus140")
                        .HasColumnType("integer");

                    b.Property<int>("Plus170")
                        .HasColumnType("integer");

                    b.Property<int>("Plus180")
                        .HasColumnType("integer");

                    b.Property<int>("SetsLost")
                        .HasColumnType("integer");

                    b.Property<int>("SetsWon")
                        .HasColumnType("integer");

                    b.Property<int>("TonPlusCheckouts")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("WorstLegDarts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("MatchPlayerStatistics");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.NotificationSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("NotificationPreference")
                        .HasColumnType("integer");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAccountName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "UserAccountName", "Endpoint")
                        .IsUnique();

                    b.ToTable("NotificationSubscriptions");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAutodartsAccount")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManager")
                        .HasColumnType("boolean");

                    b.Property<int>("NotificationPreference")
                        .HasColumnType("integer");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<int>("SeedPot")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "AccountName")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.ScoringCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Type")
                        .IsUnique();

                    b.ToTable("ScoringCriteria");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AreGameModesLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("DiscordWebhookDisplayText")
                        .HasColumnType("text");

                    b.Property<string>("DiscordWebhookUrl")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<int>("GroupDrawMode")
                        .HasColumnType("integer");

                    b.Property<int>("GroupMode")
                        .HasColumnType("integer");

                    b.Property<int>("GroupOrderMode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRegistrationOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("KnockoutsPerRound")
                        .HasColumnType("integer");

                    b.Property<int>("LegFactor")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesPerOpponent")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OrganizerAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanningVariant")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersPerTeam")
                        .HasColumnType("integer");

                    b.Property<int>("PlayoffAdvancers")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RegistrationEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RegistrationStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeedTopCount")
                        .HasColumnType("integer");

                    b.Property<bool>("SeedingEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("TeamplayEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ThirdPlaceMatch")
                        .HasColumnType("boolean");

                    b.Property<int>("Variant")
                        .HasColumnType("integer");

                    b.Property<int>("WinPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasFilter("\"JoinCode\" IS NOT NULL");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.TournamentRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseScore")
                        .HasColumnType("integer");

                    b.Property<int>("BoardAssignment")
                        .HasColumnType("integer");

                    b.Property<string>("BullMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BullOffMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("FixedBoardId")
                        .HasColumnType("uuid");

                    b.Property<int>("GameMode")
                        .HasColumnType("integer");

                    b.Property<string>("InMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("LegDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Legs")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRounds")
                        .HasColumnType("integer");

                    b.Property<int>("MinPlayerPauseMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("OutMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PauseBetweenMatchesMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("Sets")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Phase", "RoundNumber")
                        .IsUnique();

                    b.ToTable("TournamentRounds");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.UserViewPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAccountName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ViewContext")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountName", "ViewContext")
                        .IsUnique();

                    b.ToTable("UserViewPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
