// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ddpc.DartSuite.Infrastructure.Persistence;

#nullable disable

namespace ddpc.DartSuite.Infrastructure.Migrations
{
    [DbContext(typeof(DartSuiteDbContext))]
    partial class DartSuiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoardManagerUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentMatchLabel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalBoardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastExtensionPollUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocalIpAddress")
                        .HasColumnType("text");

                    b.Property<int>("ManagedMode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalBoardId")
                        .IsUnique();

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayLegs")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("AwaySets")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalMatchId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<int>("HomeLegs")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeSets")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBoardLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStartTimeLocked")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PlannedStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WinnerParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Phase", "Round", "MatchNumber")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAutodartsAccount")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManager")
                        .HasColumnType("boolean");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "AccountName")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.ScoringCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Type")
                        .IsUnique();

                    b.ToTable("ScoringCriteria");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AreGameModesLocked")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<int>("GroupDrawMode")
                        .HasColumnType("integer");

                    b.Property<int>("GroupMode")
                        .HasColumnType("integer");

                    b.Property<int>("GroupOrderMode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRegistrationOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("KnockoutsPerRound")
                        .HasColumnType("integer");

                    b.Property<int>("LegFactor")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesPerOpponent")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OrganizerAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanningVariant")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersPerTeam")
                        .HasColumnType("integer");

                    b.Property<int>("PlayoffAdvancers")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RegistrationEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RegistrationStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("TeamplayEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ThirdPlaceMatch")
                        .HasColumnType("boolean");

                    b.Property<int>("Variant")
                        .HasColumnType("integer");

                    b.Property<int>("WinPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasFilter("\"JoinCode\" IS NOT NULL");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("ddpc.DartSuite.Domain.Entities.TournamentRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseScore")
                        .HasColumnType("integer");

                    b.Property<int>("BoardAssignment")
                        .HasColumnType("integer");

                    b.Property<string>("BullMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BullOffMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("FixedBoardId")
                        .HasColumnType("uuid");

                    b.Property<int>("GameMode")
                        .HasColumnType("integer");

                    b.Property<string>("InMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Legs")
                        .HasColumnType("integer");

                    b.Property<int>("MatchDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRounds")
                        .HasColumnType("integer");

                    b.Property<int>("MinPlayerPauseMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("OutMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PauseBetweenMatchesMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("Sets")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Phase", "RoundNumber")
                        .IsUnique();

                    b.ToTable("TournamentRounds");
                });
#pragma warning restore 612, 618
        }
    }
}
