namespace ddpc.DartSuite.Application.Contracts.Tournaments;

public sealed record TournamentDto(
    Guid Id,
    string Name,
    string OrganizerAccount,
    string Status,
    DateOnly StartDate,
    DateOnly EndDate,
    string? StartTime,
    string Mode,
    string Variant,
    bool TeamplayEnabled,
    bool IsLocked,
    bool AreGameModesLocked,
    string? JoinCode,
    int ParticipantCount,
    int GroupCount,
    int PlayoffAdvancers,
    int KnockoutsPerRound,
    int MatchesPerOpponent,
    string GroupMode,
    string GroupDrawMode,
    string PlanningVariant,
    string GroupOrderMode,
    bool ThirdPlaceMatch,
    int PlayersPerTeam,
    int WinPoints,
    int LegFactor,
    bool IsRegistrationOpen = false,
    DateTimeOffset? RegistrationStartUtc = null,
    DateTimeOffset? RegistrationEndUtc = null,
    string? DiscordWebhookUrl = null,
    string? DiscordWebhookDisplayText = null,
    bool SeedingEnabled = false,
    int SeedTopCount = 0);