# fly.toml app configuration file generated for dartsuite on 2026-03-28T23:32:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dartsuite'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"
  build-target = "build"
  context = "./src/ddpc.Dartsuite.Web"
