#
name: Release API

on:
  workflow_dispatch:

jobs:
  release-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout publish-api branch
        uses: actions/checkout@v4
        with:
          ref: publish-api

      - name: Pull main into publish-api
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin main
          git merge origin/main --no-edit

      - name: Set remote URL to use PAT for push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Push merged branch
        run: git push origin publish-api